version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql:/sql/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bot
    env_file:
      - ./.env
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
  web:
    build: .
    container_name: django
    command: bash -c "pipenv run python manage.py migrate && pipenv run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  bot:
    build: .
    container_name: tg_bot
    command: pipenv run python run_pooling.py
    env_file:
      - ./.env
    depends_on:
      - web
  celery:
    build: .
    container_name: celery
    command: pipenv run celery -A config worker --loglevel=INFO -E
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
  celery-beat:
    build: .
    container_name: celery_beat
    command: pipenv run celery -A config beat --loglevel=INFO
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery
      - web

volumes:
  postgres_data: